name: Terraform Infra

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-infra:
    name: Terraform Infra
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform/infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::978937106980:role/terraform-github-ci-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14

      - name: Terraform Init
        run: terraform init

      - name: Terraform Lint (fmt + validate)
        id: lint
        run: |
          terraform fmt -check -recursive
          terraform validate

      - name: Terraform Plan
        if: ${{ success() }}
        run: terraform plan -out=tfplan